CT
htylab/tigerbx pull request #50
Opened 2023-11-26 10:45 UTC by pengushow

add cortical thickness,ct model is tigerbx\tigerbx\mprage_mix_ct.onnx

2023-11-27 23:02 UTC, htylab requested changes
onnx file should be removed.

2023-11-28 02:50 UTC, pengushow commented
delete onnx file

2023-11-28 02:50 UTC, pengushow commented
delete onnx file

2023-11-28 09:54 UTC, pengushow commented
bet input

2023-11-29 06:50 UTC, merged